1/2 swiftlint: don't use --fix & disable unused_optional_binding
Motivation:
1. There is a swiftlint bug that doesn't show some diagnostics messages if --fix is used :( (e.g.
   unused_optional_binding, custom_rules)
2. Now, I can drop check_uncommitted_files in format.sh and tests.sh. We won't longer require clean git tree before
   tests could be run! Yay! I will do that in the next commit

Disable unused_optional_binding, because I prefer `let _` over `!= nil` check in SequenceEx

   /Users/bobko/a/AeroSpace/Sources/Common/util/SequenceEx.swift:122:19: error: Unused Optional Binding Violation: Prefer `!= nil` over `let _ =` (unused_optional_binding)